baseURL = "https://www.deliveryconf.com/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "DeliveryConf"
theme = "meghna-hugo"
summaryLength = 10

# Allow HTML
[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

# Menu
[menu]
    
    [[menu.nav]]
    name = "Speakers"
    URL = "#keynote-nav"
    weight = 1

    [[menu.nav]]
    name = "About"
    URL = "#about-nav"
    weight = 2

    [[menu.nav]]
    name = "Format"
    URL = "/format"
    weight = 3

    # [[menu.nav]]
    # name = "Propose"
    # URL = "#propose-nav"
    # weight = 4

    [[menu.nav]]
    name = "Register"
    URL = "#register-nav"
    weight = 5

    [[menu.nav]]
    name = "Sponsor"
    URL = "#sponsor-list-nav"
    weight = 6

    [[menu.nav]]
    name = "Location"
    URL = "#location-nav"
    weight = 7

    [[menu.nav]]
    name = "Team"
    URL = "#our-team-nav"
    weight = 8

    [[menu.nav]]
    name = "Conduct"
    URL = "/conduct"
    weight = 9

# Site params
[params]
home= "Home"
logo = "images/logos/delivery-conf-logo-dates-narrow.jpg"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "Continuous Integration / Continuous Delivery conference"
author = "DeliveryConf"
# Google Analitycs
googleAnalitycsID = "UA-146286048-1"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = false
    bgImage = "images/slider/hero-area.jpg"
    icon = "tf-ion-play"
    heading = "Learning from today - Shaping tomorrow"
    content= "It's been 10 years since the CD book came out. How are we tackling hard problems today? What's next? What will we need tomorrow? Join us to investigate and learn."
    btn = true
    btnText="Explore Us"
    btnURL="#services"

    # call to action
    [params.cta]
    enable = true
    title = "Learning from today - Shaping tomorrow"
    content = "It's been 10 years since the CD book came out. How are we tackling hard problems today? What's next? What will we need tomorrow? Join us to investigate and learn."
    btnURL = "#register"
    btnText = "Register Now"
    btnId = "register-btn"

    # counter
    [params.counter]
    enable = false
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Days"
        icon = "tf-ion-android-happy"
        count = "2"

        [[params.counter.counterItem]]
        title = "Tracks"
        icon = "tf-ion-archive"
        count = "3"

        [[params.counter.counterItem]]
        title = "Speakers"
        icon = "tf-ion-thumbsup"
        count = "2"

        [[params.counter.counterItem]]
        title = "Cups of Coffee"
        icon = "tf-ion-coffee"
        count = "2500"

    # speakers
    [params.speakers]
    enable = true
    title = "Speakers"
    
    # about us
    [params.about]
    enable = true
    title = "About Us"

    # propose
    [params.propose]
    enable = false
    title = "Propose"

    # register
    [params.register]
    enable = true
    title = "Register"

    # sponsor
    [params.sponsor]
    enable = true
    title = "Sponsor"

    # location
    [params.location]
    enable = true
    title = "Location"

    # team
    [params.team]
    enable = true
    title = "Our Team"




    # footer
    [params.footer]
        copyright = "Themefisher Team"
        copyrightURL = "http://www.themefisher.com"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "https://twitter.com/deliveryconf"
        target = "_blank"

        [[params.footer.socialIcon]]
        icon = "tf-ion-email"
        url = "mailto:DeliveryConf Organizers<organizers@deliveryconf.com>?subject=Question from the website"
        target = "_blank"
